spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/dbTest
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update